Import ('env')

name = 'biopp-filer'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['biopp-filer', 'biopp','gmock','gtest_main']
CXXFLAGS = ['-Wall', '-Wextra', '-Wno-sign-compare']

env.Replace(CXXFLAGS=CXXFLAGS, CFLAGS=CXXFLAGS)

env.CreateTest(name, inc, src, deps)
